### ISSUE TITLE
I have to restore pages after every Firefox upgrade (upgrading from an erlier Firefox Quantum version)

### ISSUE THREAD

**Issue by gl1000007** [sneakypete81/updatescanner#189]
* Firefox version: 57.0.3, 32 bit
* Update Scanner version: 4.2.0
Windows 10

#### Steps to reproduce the problem:
I just updated Firefox to 57.0.3 from an earlier Quantum version, only to see that my pages are gone, as if had a new Update Scanner install or upgraded Firefox to Quantum.

#### What you expected to happen:
I've expected the pages to stay exactly where they are. This is maybe the second or third time for me, as it occurs every single time I update Firefox since moved to Quantum.

#### What actually happened:
Specifically for me, I already know how to export my bookmarks and import them to Update Scanner, but doing so time after time is very annoying.

**Comment by gl1000007** [comment]
Update: It happens after every time Firefox Crashes (!)

**Comment by einst3** [comment]
Agree, please make permanent storage on drive so settings don't get lost. 
Also add a clear all to the settings because if something goes bonkers i would like to remove my current and then restore from my backup.
I always backup my settings because i have lost my settings too. Now i am more careful so after a change i backup the settings to json file so i can re-import after they go missing.

**Comment by sneakypete81** [comment]
Tracked in #149
