### ISSUE TITLE
Option to disable highlighting?

### ISSUE THREAD

**Issue by roooots** [sneakypete81/updatescanner#194]
Hi,

the old addon had the option to enable/disable highlighting of differences, 4.2.0 in 57.0.4 appears to come without that switch. As I mostly monitor sites which load images using JS, images are missing, which is a problem.

Is there any workaround?

Thanks.
r.

**Comment by sneakypete81** [comment]
On the page showing the pages, you can click the page title at the top of the header to go to the actual page. Does that help?

**Comment by johnhawkinson** [comment]
The fact that the page title is a link is hard to notice, because it lacks the normal affordance for clicking that links have: it's not blue.

That seems to be because of this:
https://github.com/sneakypete81/updatescanner/blob/5997b89fee74e0d52a3e7ca7d4751a3f7310e9d5/src/app/main/main.css#L36-L37

Can the css be adjusted so that page titles look like clickable links?
Please let me know if you'd rather I open a new Issue for this. Thanks.
