### ISSUE TITLE
UI Change Suggestion: Autoscan, Change Threshold

### ISSUE THREAD

**Issue by einst3** [sneakypete81/updatescanner#201]
UI Change Suggestion: Autoscan, Change Threshold...
1) add Autoscan dropdown/slider for the time length you need to check like [second, minute, hour, day, week, month, manual] 
2) add Change Threshold number textbox/up-down to allow you to type/click the number. if not add 20,40,50,70 chars.
3) default setting to 1 week 100 chars.

**Comment by sneakypete81** [comment]
Can you explain a bit more why the current behaviour isn't sufficient? This seems to make things more complex, so I'd like to understand why a change would help.

**Comment by btanner2** [comment]
Hi,

the reason is simple. Normal day in the office takes about 8 hours + break. Normally I would like to check a page twice per working day, this would mean every 4 hours. Unfortunately this cannot be chosen. I am pretty sure every user does have different conditions how to use. In my opinion the options in which hours are included are a bit underrepresented:

1 hour - 6 hours 

If it comes to the different choosable values, I cannot imagen that someone use minutes, because he would get crazy if every 5 Minutes a popup with a change will appear. Maybe the hour related values should be extended a bit. I think 1, 2, 4, 8 would be perfect values for this

Kind regards

**Comment by sneakypete81** [comment]
> the reason is simple. Normal day in the office takes about 8 hours + break. Normally I would like to check a page twice per working day, this would mean every 4 hours.

Any problem with using a 1-hour setting? Then you can look at it every 4 hours and you're guaranteed to see all updates since the last hour. You also get an update every hour, in case you want to see changes more often.

I think of this setting as "If I choose to look at the current page status, how up-to-date do I want it to be?". So setting it to "1 week" is probably not very useful, since it might be _very_ out of date.

**Comment by sneakypete81** [comment]
Thanks for the idea, but I'm reluctant to change this UI since the 1 hour setting seems appropriate for the use case you describe.

**Comment by einst3** [comment]
it would be nice to have a two week option.
