### ISSUE TITLE
BUG: No detection if a page with 404 changed to normal content (NO 404 anymore)

### ISSUE THREAD

**Issue by btanner2** [sneakypete81/updatescanner#213]
Hi,

I used the Update Scanner to watch pages which delivers a 404 right now, but which will have content in the feature. Here is a simple example:

This page exists right now:

http://download.avm.de/dect/0606/c16/info_06.06.04.66.txt

These pages do not exist right now:

http://download.avm.de/dect/0606/c16/info_06.06.04.67.txt
http://download.avm.de/dect/0606/c16/info_06.06.04.68.txt
http://download.avm.de/dect/0606/c16/info_06.06.04.69.txt
http://download.avm.de/dect/0606/c16/info_06.06.04.70.txt

but they will in the future, if the related firmware gets an update from the manufacturer.

Unfortunately Update Scanner does not recognize if a non-existing page turns into an existing page. This is very sad. Could you please fix this?

Thanks for your great add-on.

Kind regards
Brian

Firefox: 58.0.2 (64-Bit)
Update Scanner: 4.2.0

**Comment by sneakypete81** [comment]
This is a bit tricky. Imagine the case where all pages fail to scan due to network problems. Then when the scan is next successful, every single page will be reported as updated, even if none have changed.

I see what you're trying to do, but it's not quite in scope of this add-on. If there's a page somewhere that links to the latest firmware version, you'd be better off scanning that page rather than speculatively scanning pages that don't exist yet.
