### ISSUE TITLE
Twitter "detected that JavaScript is disabled in your browser" 

### ISSUE THREAD

**Issue by AJCxZ0** [sneakypete81/updatescanner#240]
Starting some time in past week or so opening any Twitter page, e.g. https://twitter.com/StevenWilsonHQ, shows a page which very quickly redraws to one with just the error,

> We've detected that JavaScript is disabled in your browser. Would you like to proceed to an older version of Twitter?

The "View Old Page" drop-down shows the page as normal, but "View New Page" shows the page with the above error. Loading the page directly shows the page as normal.

Update Scanner 4.3.0 on Firefox 59.0.2 (64-bit) on Ubuntu 16.04.4 LTS.

**Comment by fatboyburns** [comment]
came to report identical problem.

Update Scanner 4.3.0 on Firefox 59.0.2 (64-bit) on Windows10 Home Ver1709.

Thanks.

**Comment by sneakypete81** [comment]
Update Scanner displays pages in a sandbox with Javascript disabled, to guard against malicious pages.

It seems that Twitter have made a change recently and longer show the page content when Javascript is disabled. The scanner is still detecting changes, but they can't be displayed by Update Scanner. If you click the title in the header, it will open the page at twitter.com, so you can at least see the current page even if there's no change highlighting.

Unfortunately I can't see any way around this.

**Comment by AJCxZ0** [comment]
Thanks for looking into this. I've not been able to determine any Javascript-free or non-intercepted Twitter page which can be scanned.

**Comment by sneakypete81** [comment]
Using version 4.2.1beta1 with Tracking Protection enabled seems to help with this - probably because Tracking Protection is inadvertently breaking the page layout. It doesn't look pretty, but you can see the updated text.

See #36 for how to install Update Scanner beta versions.

To enable tracking protection, go to Firefox Preferences, click "Privacy and Security" then set Tracking Protection to "Always".

**Comment by AJCxZ0** [comment]
4.3.1beta1 installed. With Tracking Protection "Always" pages render apparently without style but with changes highlighted, however without the style they are almost useless.

Oddly, while pages were scanned and rendered fine with Tracking Protection "Never" in the current release, now they give the "detected that JavaScript is disabled in your browser" error!

As if that wasn't strange enough, when the Twitter page is loaded directly, Firefox reports, "No tracking elements detected on this page", but in the Update Scanner page Privacy Badger filters a doubleclick and a Google Analytics tracker.

**Comment by sneakypete81** [comment]
@AJCxZ0 - good to hear the beta fixes your scanning problem.

Regarding the strange display behaviour, this is due to a Firefox limitation described in https://bugzilla.mozilla.org/show_bug.cgi?id=1404610#c15. Update Scanner uses a sandboxed iframe to display the site content, and all requests from this iframe are subject to Tracking Protection blocking. Hopefully this will be fixed in a future Firefox version - there seem to be lots of problems at the moment with WebExtension interactions with Tracking Protection and Private Browsing.

That's a different issue to this one though. The "Javascript is disabled" message is not something that's fixable, as far as I can see.
