### ISSUE TITLE
Marked as seen - sync

### ISSUE THREAD

**Issue by SteveP-UK** [sneakypete81/updatescanner#248]
Hiya

Loving this add-on. Thanks for developing it. I can see a similar question has been asked before but I think my request is slightly different.

I have two PCs and I wondered if there's a way that when I've clicked on the UpdateScanner link and visited the site on PC1, this 'state' could by synced across to another PC - PC2? My thinking is to use something like DropBox and use a symbolic link in DB to wherever the 'changed state' is stored on PC1 and then DropBox it to PC2. Appreciate your thoughts. I know the symbolic link idea works as I use it for other synced data on my PC that lives outside DB - I just need to know if the changed state is stored in a folder somewhere?

Cheers
Steve

**Comment by sneakypete81** [comment]
It should be possible to synchronise the list of sites across different computers, but the currently downloaded HTML is stored using IndexedDB rather than storage.local. I can't see a way of easily synchronising both of these, unfortunately.

The currently downloaded HTML can possibly be found here: https://stackoverflow.com/questions/5358704/where-are-firefox-indexeddb-files-stored#5359128

**Comment by SteveP-UK** [comment]
Nope. Dead end. The HTML files are note located in the indexed dB folder. Never mind!
