### ISSUE TITLE
Add requireInteraction property to notifications

### ISSUE THREAD

**Issue by Gitoffthelawn** [sneakypete81/updatescanner#365]
Can you add the [requireInteraction property](https://developer.mozilla.org/docs/Web/API/notification/requireInteraction) to the notifications?

This way, users can voluntarily set the `dom.webnotifications.requireinteraction.enabled` preference to true to allow the notifications to persist until closed by the user.

My understanding is that this will not affect users who choose not to set `dom.webnotifications.requireinteraction.enabled` to true.

Thanks!

**Comment by sneakypete81** [comment]
Unfortunately the [WebExtension Notifications API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications) doesn't have this option.

**Comment by Gitoffthelawn** [comment]
Thanks.  You're right.  Would using notifications.update() ( https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/notifications/update ) keep it open if you kept updating it?

Of course, that's more work than simply adding a property.

**Comment by Gitoffthelawn** [comment]
Also, what about adding an optional sound that coincides when the notification is created?

**Comment by Atamasy** [comment]
> 
> 
> Also, what about adding an optional sound that coincides when the notification is created?

Sneakypete81 stated that the new Quantum based Firefox uses OS based notifications and implementing sound would be difficult. I'll admit I haven't dug into the development guide for Firefox and have limited experience with legacy extensions, but Distill Monitor works with sound as it did when it was a legacy extension. 

I chose to use Update Scanner since it hit the addon market and I always liked Pete's extension because it was fast, lightweight and simple to use. Two features stood out for me compared to Distill back then.

1. Persistent notification with sound
2. The ability to select text mass difference; "Ignore any changes less than 50 chars"

-It takes way too freaking long to set up Distill for every page using varying second;minute;hour checks and set it up to monitor specific areas and set up variables to check for _X_ chars change variables.

**Comment by Atamasy** [comment]
test

**Comment by Atamasy** [comment]
.....

**Comment by Atamasy** [comment]
test

**Comment by Atamasy** [comment]
test
