### ISSUE TITLE
Why is Updatescanner so broken on Patreon?

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#525]
To help explain the issue, please include the following:
 * OS version: Windows 10 build 1903
 * Firefox version: 69.0b7
 * Update Scanner version: 4.5.0beta1

#### Steps to reproduce the problem:
Go to any patreon site and add it to be scanned. You can sit there all day long just saying update page and it will show changed!  

#### What you expected to happen:
page to report it has not changed once I have viewed it.

#### What actually happened:
The page goes back to bold indicating that it has changed.

**Comment by molitar** [comment]
Still having this problem Updatescanner really really hates Patreon pages.

**Comment by sneakypete81** [comment]
it works for me, although some of the content doesn't display since the site requires Javascript. Please include a URL in your report, so I can test the same page as you.

In general though, to see why a page was identified as changed, see the instructions at https://github.com/sneakypete81/updatescanner/wiki#how-do-i-see-why-a-page-was-identified-as-changed.

**Comment by sneakypete81** [comment]
Closing for now, please update if you can provide further information.
