### ISSUE TITLE
Mark changes with << >> only works when highlighting is enabled

### ISSUE THREAD

**Issue by StVol33** [sneakypete81/updatescanner#78]
This option does not work alone! It works only with "highlight change" .

**Comment by sneakypete81** [comment]
Thanks, good catch. There's a bug in the logic for this.

**Comment by sneakypete81** [comment]
When "highlight changes" is off, clicking on the item in the sidebar causes the page to be loaded as a normal link (ie. not via Update Scanner). We need to keep this behaviour, since it can be used to work around pages that don't display properly when loaded through Update Scanner.

This means that the proper fix for this bug is to disable the "Mark changes with << >" option if "highlight changes" is off.

**Comment by StVol33** [comment]
"Mark changes with << >>" дублирует  "highlight change"! Показывает:  **и** цвет **и** <<  >>! Хотелось бы видеть **или** цвет **, или**   <<  >>! 
"Mark changes with << >>" duplicate "highlight change"! Shows:  color **and** << >>! I would like to see the color **or**  << >>!
